### ISSUE TITLE
Move the 2016 hackathon website to 2016.cytodata.org

### ISSUE THREAD

**Issue by shntnu** [cytodata/cytodata-2016#3]
hack.cytominr.org should be moved to cytodata.org/2016

**Comment by shntnu** [comment]
@N3llz @cells2numbers I've moved this site to the cytodata org, and deployed using netlify at https://cytodata-2016.netlify.com/
Lets have it at 2016.cytodata.org (easier that doing cytodata.org/2016 IIUC)

**Comment by shntnu** [comment]
We'd also want to have http://hack.cytominr.org/ redirect to 2016.cytodata.org

**Comment by N3llz** [comment]
all set here

**Comment by shntnu** [comment]
@N3llz Does it actually redirect to 2016.cytodata.org?

Or is that it is (additionally) being published at http://hack.cytominr.org/?

**Comment by shntnu** [comment]
Confirmed that it was being published at http://hack.cytominr.org/, which is no longer the case because I disabled ghpages.
@N3llz Can you set up redirect? hack.cytominr.org -> 2016.cytodata.org

**Comment by N3llz** [comment]
Ok, now it's all set!
